### ISSUE TITLE
EIP 8 Compliance

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-devp2p#11]
[EIP 8](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-8.md) compliance for this library is needed in order to being usable again. At the moment, ``EIP 8`` (forwards compatibility) changes aren't implemented, and the library can't build up connection to more or less any up-to-date node.

This behavior can be observed by e.g. running the ``peer-communication`` example.

There are three parts to this EIP:

### Changes to the devp2p Wire Protocol

(Probably) implemented

### Changes to the RLPx Discovery Protocol

(Probably) implemented

### Changes to the RLPx TCP Handshake

At least the [RLPx TCP Handshake](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-8.md#changes-to-the-rlpx-tcp-handshake) part isn't implemented and has to be added to ``Auth`` and ``Ack`` encoding/decoding in [rlpx/peer.js](https://github.com/ethereumjs/ethereumjs-devp2p/blob/master/src/rlpx/peer.js) and [rlpx/ecies.js](https://github.com/ethereumjs/ethereumjs-devp2p/blob/master/src/rlpx/ecies.js).

At least the ``Ack`` receival part is necessary to build a robust network with peers from the DPT.

The implementation in the [pydevp2p](https://github.com/ethereum/pydevp2p/blob/develop/devp2p/rlpxcipher.py) library is well-structured and can serve as a basis and for orientation.

Note:
There are some basic [unit tests](https://github.com/ethereumjs/ethereumjs-devp2p/blob/master/test/eip-8-discovery.js) on ``EIP 8``, these tests are not doing much though and doesn't hint to ``EIP 8`` being already implemented.

**Comment by holgerd77** [comment]
Ah, just saw on a second look, the unit tests don't do that much testing though.

**Comment by fanatid** [comment]
Sorry do not know nothing about EIP8 compliance.

**Comment by holgerd77** [comment]
Ok, thanks.

**Comment by holgerd77** [comment]
Copied chat extract from ``ethereum/devp2p`` channel for reference:

My Message:

Hi @fjl, I'm trying to have a look at ``EIP-8`` for the ``ethereumjs-devp2p`` implementation, concretely the [Changes to the RLPx TCP handshake](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-8.md#changes-to-the-rlpx-tcp-handshake) part.

I'm a bit stuck at the implementation of:

```
packet = read(307, connection)
if decrypt(packet) {
    // process as old format
} else {
    size = unpack_16bit_big_endian(packet)
    packet += read(size - 307 + 2, connection)
    if !decrypt(packet) {
        // error
    }
    // process as new format
}
```

And especially this ``decrypt(packet)`` switch. What would actually make this evaluate to ``false``? Can you give me a hint? Would be really helpful!

@fjl And is this only for the ``Auth`` package (sorry, I'm really no expert here, hope my questions make somewhat sense)?

Answer from @hayesgm:
According to EIP-8, the packet now starts with `auth-packet      = auth-size || enc-auth-body`

If the packet doesn't start with the `auth-size` or encoding, we assume that it may not be a valid EIP-8 packet, but still might be a valid pre-EIP-8 packet and try to decode it as such.

(Though, I think most implementations go the other way and try to decode it as a pre-EIP-8 and failing that, try to decode it as EIP-8)

To be a valid pre-EIP-8 message, it has to start with the ECIES data, which makes it pretty trivial to reject invalid packets.  E.g.

(from Exthereum)

 ```
          0x04::size(header_size_bits),                              # header
          her_ephemeral_public_key_raw::binary-size(public_key_len), # public key
          cipher_iv::binary-size(key_len),                           # cipher iv
          encoded_message::binary-size(encoded_message_len),         # encoded_message
          message_tag::binary-size(hash_len)>> ->                    # message tag
```

**Comment by holgerd77** [comment]
Another Gitter ``ethereum/devp2p`` reference:

My question:

Hi, I'm trying to bring a package starting e.g. with ``<Buffer 04 10 55 0b 30 c3`` together with the following formula from ``EIP-8``:

```
packet = read(307, connection)
if decrypt(packet) {
    // process as old format
} else {
    size = unpack_16bit_big_endian(packet)
    packet += read(size - 307 + 2, connection)
    if !decrypt(packet) {
        // error
    }
    // process as new format
}
```

As size I would take the two hex values after the initial ``0x04`` buffer value, so ``10 55``, which would be 4181 as decimal, so ``size = 4181``.

I would then additionally read (cause of ``+=``) ``4181 - 307 + 2 = 3876`` buffer values according to the ``packet += read(size - 307 + 2, connection)`` line.

Wouldn't that be far too much? Can someone help where my error lies here?

Answer from @fjl:

The size is in the first two bytes, `04 10`
