### ISSUE TITLE
Could you please add more guides for the Run/Build in the Readme.MD?

### ISSUE THREAD

**Issue by ShifaSZ** [ethereumjs/ethereumjs-devp2p#22]
To make command "npm run build" work, I have to run "npm install --save-dev babel-cli" to solve the error in the "babel src -d lib" command, and have to run "npm install babel-plugin-transform-class-properties --save" to solve the error of 'ReferenceError: Unknown plugin "transform-class-properties" specified in .babelrc at 0'. It costed me hours searching online to solve these issues.
It will be very appreciated if you can add more guides for these errors.

**Comment by fanatid** [comment]
This packages already in package.json:

babel-cli: https://github.com/ethereumjs/ethereumjs-devp2p/blob/7c6272cd76e11e35cc7e00c8a8dcfff28cf7d4e6/package.json#L60
transform-class-properties: https://github.com/ethereumjs/ethereumjs-devp2p/blob/7c6272cd76e11e35cc7e00c8a8dcfff28cf7d4e6/package.json#L62

**Comment by jwasinger** [comment]
Also make sure you are using a newer version of NodeJS.  Using 9.4.0, I had no issues whatsoever.

**Comment by holgerd77** [comment]
The questions/problems you have are touching more the general way on how Node is installing libraries, have a look e.g. at https://stackoverflow.com/questions/34700610/npm-install-wont-install-devdependencies for a deeper understanding of that.

To document this here would be out of the scope of this library.

**Comment by ShifaSZ** [comment]
Thanks you all. I should get all the dependencies installed.
