### ISSUE TITLE
Docs Auto-Generation / Integrate API docs from old repos

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-devp2p#37]
The documentation from the old ``node-devp2p-*`` repositories didn't completely make it into the new repository.

The following docs should be checked and missing information / API description should be added to this repo:

- https://github.com/ethereumjs/node-devp2p-rlpx/tree/c246fb0cd7e64025e29d1de06feb8c4cd20dbefb
- https://github.com/ethereumjs/node-devp2p-dpt/blob/1768d764ef6948f62d1d3b5f0fc8059e14ab3d3e/API.md
- https://github.com/ethereumjs/node-devp2p/tree/c246fb0cd7e64025e29d1de06feb8c4cd20dbefb

**Comment by holgerd77** [comment]
This can be also taken in the context of an eventual discussion on auto-generation of docs on this library. I can remember that I once had a look into this and came to the conclusion that this is at least more challenging and would need additional evaluation if useful/practical together with some substantial thinking on some concept here due to the event based nature of the library and some - likely - necessary guidance along on library usage.

**Comment by ryanio** [comment]
This repository is now using typedoc for auto-generated [docs](https://github.com/ethereumjs/ethereumjs-devp2p/tree/master/docs) 👍
