### ISSUE TITLE
barbel Unknown plugin "transform-runtime"

### ISSUE THREAD

**Issue by prateektiwari7** [ethereumjs/ethereumjs-devp2p#43]
Hi I am getting this plugin error 

Alreadt tried this command

npm install babel-plugin-transform-class-properties --save

npm run build 

ReferenceError: Unknown plugin "transform-runtime" specified in "/Users/Documents/ethereum-research/ethereumjs-devp2p/.babelrc" at 1, attempted to resolve relative to "/Users/Documents/ethereum-research/ethereumjs-devp2p"

**Comment by holgerd77** [comment]
You probably haven't installed the [devDependencies](https://github.com/ethereumjs/ethereumjs-devp2p/blob/630adf262c0c671ad7c6cf17bb0d5b4a89b76415/package.json#L64) during installation process. Have a look at the link above, there is another plugin needed to be installed in this context.
