### ISSUE TITLE
RLPX Question: Shouldn't peer be removed from this._peers once it closes ?

### ISSUE THREAD

**Issue by ya7ya** [ethereumjs/ethereumjs-devp2p#5]
hey @fanatid , regarding [RLPX peer](https://github.com/ethereumjs/ethereumjs-devp2p/blob/master/es/rlpx/index.js#L175) close event, Shouldn't the peer be removed form the `this._peers` Map once the event is triggered ? not removing the peer means `this._getOpenSlots()` will return actual open slots + the peer that just closed.

the fix is simple 
```javascript
// rlpx/index.js - in peer.once('close') event handler
let peerKey = peer.getId().toString('hex')
this._peers.delete(peerKey)
```

Thanks for your help, I appreciate it. 👍

**Comment by fanatid** [comment]
`peer` is removed in socket close event: https://github.com/ethereumjs/ethereumjs-devp2p/blob/f066af06b6d09a5a4459a6a2894e68c88c349ffe/es/rlpx/index.js#L92
but, we also should remove in peer close event, because socket close not remove incoming peers
do you want make PR?

**Comment by ya7ya** [comment]
Yeah , I'm up for it. I'll submit a PR
