### ISSUE TITLE
Node version?

### ISSUE THREAD

**Issue by jtakalai** [ethereumjs/ethereumjs-devp2p#7]
Could you mention in README.md or elsewhere in docs which node version you expect? Async is used in code, introduced in 7.6; https://nodejs.org/en/ says newest features are in 8.6, recommended stable is 6.11.3 LTS. Which version are you using? Which one would you recommend?

**Comment by fanatid** [comment]
published version transplited with babel, should work with 6.x
at least on node 6.5.0 works fine

**Comment by fanatid** [comment]
package.json now contains engines field, which require node >= 6
https://github.com/ethereumjs/ethereumjs-devp2p/pull/9
