### ISSUE TITLE
Subprotocol error: network mismatch

### ISSUE THREAD

**Issue by gorgos** [ethereumjs/ethereumjs-devp2p#85]
Sometimes I get connections, but most of the times I'm seeing the network mismatch error messages. It pretty much looks like here: https://github.com/ethereumjs/ethereumjs-devp2p/issues/12#issuecomment-398211899.

I'm opening a new issue as the other one is closed and two years old.

**Comment by holgerd77** [comment]
Not a bug but just imminent behavior due to the protocol versions currently supported (this will e.g. improve on better/updated discovery protocol versions), will close.
