### ISSUE TITLE
Update to @ethereumjs/config v2.0.0

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-devp2p#91]
Preparation for #86 

This library needs to be updated to linting, typescript config and coverage setup using the [v2.0.0](https://github.com/ethereumjs/ethereumjs-config/releases) from the `@ethereumjs/config` packages.

The respective VM/monorepo PR https://github.com/ethereumjs/ethereumjs-vm/pull/913 can serve as some reference PR here.

**Comment by ryanio** [comment]
Completed in #93
